application:
  name: hasura
  project: TheParisianRestaurant
  cloud_region: aws/us-east-2
databases:
- type: postgresql
  version: "11.5"
  name: my-postgresql-database
routers:
- name: main
  custom_domains:
  - branch: master
    domain: hasura-api.qvy.io
  - branch: dev
    domain: hasura-api-dev.qvy.io
  routes:
  - application_name: hasura
    paths:
    - /*

