application:
  name: hasura
  project: TheParisianRestaurant
  cloud_region: aws/us-east-2
databases:
- type: postgresql
  version: "11.5"
  name: my-postgresql-database
routers:
- name: main
  routes:
  - application_name: hasura
    paths:
    - /*
